export interface PortfolioItem {
  id: string
  title: string
  description: string
  category: string
  highlightKeyword?: string
  images: string[]
  technologies: string[]
  demoUrl?: string
  githubUrl?: string
  completionDate?: string
  longDescription?: string
  features?: string[]
  process?: string
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: "seo-1",
    title: "Google Search",
    description: "Boost your website's visibility, traffic, and rankings with comprehensive SEO strategies tailored to your business needs.",
    category: "seo",
    highlightKeyword: "seo",
    images: ["digital/Google Search 2.png", "digital/Google Search 1.jpg", "digital/Google Search 3.png", "digital/Google Analytic.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },

  {
    id: "seo-2",
    title: "On page SEO",
    description: "Optimize your website content, structure, and HTML elements to improve search engine rankings and user experience",
    category: "seo",
    highlightKeyword: "On page SEO",
    images: ["digital/On Page SEO.png", ],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },

  {
    id: "seo-3",
    title: "Off page SEO",
    description: "Build high-quality backlinks and boost your site’s authority with proven off-page SEO strategies.",
    category: "seo",
    highlightKeyword: "Off page SEO",
    images: ["digital/backlink 1.jpeg", "digital/Local Citation.png", "digital/Web 2.0 Backlinks.png", "digital/Profile Backlinks 1.png", "digital/Guest Post 1.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },

  {
    id: "seo-4",
    title: "Technical SEO",
    description: "Enhance your website’s speed, crawlability, and indexability for better search engine performance.",
    category: "seo",
    highlightKeyword: "Technical SEO",
    images: ["digital/Technical SEO.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },

  {
    id: "seo-5",
    title: "Local SEO",
    description: "Get found by local customers with optimized listings, maps, and geo-targeted SEO tactics.",
    category: "seo",
    highlightKeyword: "Local SEO",
    images: ["digital/Local SEO.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "SEO-6",
    title: "Real Estate-Content SEO",
    description: "Optimize your real estate website for search engines and improve your online presence.",
    category: "seo",
    highlightKeyword: "Real Estate",
    images: ["digital/Web 2.0 Backlinks.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },



  {
    id: "GoogleAds-1",
    title: "Google Ads",
    description: "Drive targeted traffic and maximize ROI with expertly managed Google Ads campaigns.",
    category: "google ads",
    highlightKeyword: "Google Ads",
    images: ["digital/Google Ads 2.png", "digital/Google Ads 3.png", "digital/Google Ads 4.jpg", "digital/Google Ads 1.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "Google Ads- 2",
    title: "Job Marketplace - YouTube Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "google ads",
    highlightKeyword: "Job Marketplace",
    images: ["digital/Web 2.0 Backlinks.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "Google Ads- 3",
    title: "Online Gift Shop - Google Discovery Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "google ads",  
    highlightKeyword: "Online Gift Shop",
    images: ["digital/google discovery ads.gif"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "Google Ads- 4",
    title: "Finance Industry - Google Video Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "google ads",  
    highlightKeyword: "Finance Industry",
    images: ["digital/Google video ads.gif"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "Google Ads- 5",
    title: "Home Decor - Google Search Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "google ads",  
    highlightKeyword: "Home Decor",
    images: ["digital/Google Search Ads 3.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "Google Ads- 6",
    title: "Online Reservation Industry - Google Display Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "google ads",  
    highlightKeyword: "Online Reservation",
    images: ["digital/Google Display ads 2.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },





  {
    id: "metaads-1",
    title: "Meta Ads",
    description: "Reach your audience on Facebook and Instagram with data-driven Meta advertising strategies.",
    category: "meta ads",
    highlightKeyword: "Meta Ads",
    images: ["digital/Meta Ads.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "metaads-2",
    title: "Car Industry - Meta Lead Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "meta ads",  
    highlightKeyword: "Car Industry",
    images: ["digital/Meta Lead Ads.webp"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "metaads-3",
    title: "Woman Glasses - Meta Carousel Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "meta ads",  
    highlightKeyword: "Woman Glasses",
    images: ["digital/Meta Carousel Ads.webp"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "metaads-4",
    title: "Beauty Product Industry - Meta Video Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "meta ads",  
    highlightKeyword: "Beauty Product",
    images: ["digital/Meta Video Ads.webp"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
{
    id: "metaads-5",
    title: "Agency Industry - Meta Image Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "meta ads",  
    highlightKeyword: "Agency",
    images: ["digital/Meta Image ads.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "metaads-6",
    title: "Women Accessories Industry - Meta Massaging Ads",
    description: "e-learning deshboard for manage users and courses.",
    category: "meta ads",  
    highlightKeyword: "Women Accessories",
    images: ["digital/Meta Massaging Ads.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  

  {
    id: "blog/article-1",
    title: "Blog/Article",
    description: "Engage readers and boost SEO with well-crafted, keyword-optimized blog and article content.",
    category: "blog article",
    highlightKeyword: "Blog",
    images: ["digital/Article Writing.jpg", "digital/Blog Writing.png", "digital/Guest Post 1.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },


  {
    id: "digitalbranding-1",
    title: "Digital Branding",
    description: "Build a strong online presence and brand identity across all digital platforms.",
    category: "digital branding",
    highlightKeyword: "Digital Branding",
    images: ["digital/Digital Branding.webp"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "digitalbranding-2",
    title: "Real Estate-Digital Branding",
    description: "e-learning deshboard for manage users and courses.",
    category: "digital branding",
    highlightKeyword: "Construction",
    images: ["digital/Digital Branding real estate.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
{
    id: "digitalbranding-3",
    title: "E-commerce-Digital Branding",
    description: "e-learning deshboard for manage users and courses.",
    category: "digital branding",
highlightKeyword: "E-commerce",
    images: ["digital/Digital Branding E commarce.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
{
    id: "digitalbranding-4",
    title: "Food Industry-Digital Branding",
    description: "e-learning deshboard for manage users and courses.",
    category: "digital branding",
    highlightKeyword: "Food Industry",
    images: ["digital/Digital Branding Food.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
{
    id: "digitalbranding-5",
    title: "Training Industry-Digital Branding",
    description: "e-learning deshboard for manage users and courses.",
    category: "digital branding",
    highlightKeyword: "Training Industry",
    images: ["digital/Digital Branding Training.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
{
    id: "digitalbranding-6",
    title: "Garments-Digital Branding",
    description: "e-learning deshboard for manage users and courses.",
    category: "digital branding",
    highlightKeyword: "Garments",
    images: ["digital/Digital brand cloth.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },


  
  {
    id: "socialmedia-1",
    title: "Social Media",
    description: "Grow your audience and increase engagement with strategic social media content and management.",
    category: "social media",
    highlightKeyword: "Social Media",
    images: ["digital/Social Media.webp"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "socialmedia-2",
    title: "Grocery-Youtube",
    description: "e-learning deshboard for manage users and courses.",
    category: "social media",
    highlightKeyword: "Grocery",
    images: ["digital/Grocary youtube.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "socialmedia-3",
    title: "Real Estate-Linkedin",
    description: "e-learning deshboard for manage users and courses.",
    category: "social media",
    highlightKeyword: "Real Estate",
    images: ["digital/Linkedin Post.jpeg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "socialmedia-4",
    title: "Women Clothing Industry-Instagram",
    description: "e-learning deshboard for manage users and courses.",
    category: "social media",
    highlightKeyword: "Women Clothing",
    images: ["digital/instagram women cloths.png"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "socialmedia-5",
    title: "Manufacture Industry-Facebook",
    description: "e-learning deshboard for manage users and courses.",
    category: "social media",
    highlightKeyword: "Manufacture Industry",
    images: ["digital/manufacture facebook.jpg"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
  {
    id: "socialmedia-6",
    title: "Online Shop-Tiktok",
    description: "e-learning deshboard for manage users and courses.",
    category: "social media",
    highlightKeyword: "Online Shop",
    images: ["digital/tiktok.webp"],
    technologies: ["Node.js", "Socket.io", "PostgreSQL"],
    demoUrl: "https://example.com/demo",
    githubUrl: "https://github.com/example/project",
    completionDate: "August 2023",
    features: [
      "Real-time message delivery",
      "User presence detection",
      "Message history storage",
      "End-to-end encryption",
    ],
  },
]


export const sectionInfo = {
  "seo": {
    "title": "SEO",
    "description": "Transform Your Online Presence with Expert SEO."
  },
  "google ads": {
    "title": "Google Ads",
    "description": "High-Converting Google Ad Campaigns"
  },
  "meta ads": {
    "title": "Meta Ads",
    "description": "Reach Customers on Social with Meta Ads"
  },
  "blog/article": {
    "title": "Blog/Article",
    "description": "Content That Connects and Converts"
  },
  "digital branding": {
    "title": "Digital Branding",
    "description": "Crafting Identities that Stand Out"
  },
  "social media": {
    "title": "Social Media",
    "description": "Grow Your Brand Through Social"
  }

}
